"""Configurable weights for the Project Gridiron rating engine."""

OFFENSE_WEIGHT = 0.45
DEFENSE_WEIGHT = 0.40
DISCIPLINE_WEIGHT = 0.15
SITUATIONAL_WEIGHT = 0.00

TOTAL_WEIGHT = (
    OFFENSE_WEIGHT
    + DEFENSE_WEIGHT
    + DISCIPLINE_WEIGHT
    + SITUATIONAL_WEIGHT
)